arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_01
    - arm_joint_02
    - arm_joint_03
    - arm_joint_04
  gains:
    arm_joint_01:
      p: 10
      d: 0
      i: 3
      i_clamp: 0
    arm_joint_02:
      p: 10
      d: 0
      i: 3
      i_clamp: 0
    arm_joint_03:
      p: 10
      d: 0
      i: 3
      i_clamp: 0
    arm_joint_04:
      p: 10
      d: 0
      i: 3
      i_clamp: 0
